version: '3.1'

networks:
  odoo8_net:
    ipam:
      config:
        - subnet: 123.45.0.0/24

services:
  db:
    image: postgres:9.6
    container_name: odoo8_db
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      odoo8_net:
        ipv4_address: 123.45.0.2
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo8_web
    depends_on:
      - db
    ports:  # use same port setting in config/odoo.conf
      - "9069:8069/tcp"
      - "9071:8071/tcp"
    volumes:
      - web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    networks:
      odoo8_net:
        ipv4_address: 123.45.0.4
    environment:
      - USER=odoo
      - PASSWORD:odoo
    restart: always

volumes:
  db-data:
    driver: local
  web-data:
    driver: local
